export { default as Home } from './Home'
export { default as Blog } from './Blog'
export { default as Shop } from './Shop'
export { default as Gallery } from './Gallery'
export { default as ConactUs } from './ConactUs'
export { default as ErrorPage } from './ERROR_PAGE'